# Generated by Django 4.0.3 on 2022-07-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtokentoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authtokenToken',
        ),
    ]
