# Generated by Django 4.0.5 on 2022-11-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='participant')),
            ],
            options={
                'verbose_name': 'Победитель',
                'verbose_name_plural': 'Победители',
            },
        ),
    ]
