# Generated by Django 4.0.3 on 2022-06-24 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.ManyToManyField(related_name='votes', to='competition.competition', verbose_name='competition')),
                ('user_id', models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('voted_for', models.ManyToManyField(related_name='votes', to='participant.participant', verbose_name='voted_for')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
    ]
