# Generated by Django 4.0.3 on 2022-06-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participant', '0002_alter_participant_participations_number'),
        ('competition', '0001_initial'),
        ('votes', '0002_remove_votes_competition_id_votes_competition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='competition_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.competition', verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='voted_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='voted_for'),
        ),
    ]
