# Generated by Django 4.0.5 on 2022-11-12 23:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2022, 11, 13), verbose_name='Дата создания')),
                ('concluded_at', models.DateField(default=None, null=True, verbose_name='Дата создания')),
                ('cover', models.ImageField(upload_to='competition/cover', verbose_name='Обложка')),
                ('nomination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='nomination.nomination', verbose_name='nomination')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to=settings.AUTH_USER_MODEL, verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
    ]
