# Generated by Django 4.0.5 on 2022-11-30 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='nomination_id',
            new_name='nomination',
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 11, 30), verbose_name='Дата создания'),
        ),
    ]
