# Generated by Django 4.0.3 on 2022-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AddField(
            model_name='competition',
            name='cover',
            field=models.ImageField(default='https://default.ru', upload_to='competition/cover', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
