# Generated by Django 4.0.5 on 2022-11-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_rename_nomination_id_competition_nomination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='nomination',
            new_name='nomination_title',
        ),
    ]
