# Generated by Django 4.0.3 on 2022-07-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_organizer_competitions_number'),
        ('competition', '0002_alter_competition_options_competition_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='organizer.organizer', verbose_name='organizer'),
        ),
    ]
