# Generated by Django 4.0.5 on 2023-01-04 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_vote_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 18, 22, 59, 277496, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
