# Generated by Django 4.0.3 on 2022-07-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_organizer_competitions_number'),
        ('competition', '0004_remove_competition_organizer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='organizer_id',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='organizer.organizer', verbose_name='organizer'),
            preserve_default=False,
        ),
    ]
