# Generated by Django 4.0.5 on 2023-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_remove_vote_user_id_vote_user_alter_vote_voted_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
