# Generated by Django 4.0.5 on 2022-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_organizer_competitions_number'),
        ('competition', '0005_remove_competition_organizer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='organizer_id',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer_id',
            field=models.ManyToManyField(related_name='competition', to='organizer.organizer', verbose_name='organizer'),
        ),
    ]
