# Generated by Django 4.0.5 on 2023-01-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_nomination_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
