# Generated by Django 4.0.5 on 2023-01-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_rename_organizer_id_competition_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
