# Generated by Django 4.0.3 on 2022-07-08 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0007_remove_competition_organizer_id_and_more'),
        ('participant', '0002_alter_participant_participations_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='competition_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='competition_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='competition.competition', verbose_name='competition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
